In [1]:
import numpy as np

In [9]:
#array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [5]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])
print(M)
print(M.shape) #(2,3) - 2 raws, 3 columns

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
#vectorized operations
a = np.array([1, 2, 3, 4])
print(a + 10)
print(a * 2)
print(a ** 2) #powered

[11 12 13 14]
[2 4 6 8]
[ 1  4  9 16]


In [11]:
#random numbers
np.random.seed(42) #фіксує випадковість
r = np.random.random(5) # 5 чисел від 0 до 1
z = np.random.standard_normal(5) # 5 чисел із нормального стандартного розподілу
print(z) 

[ 0.27904129  1.01051528 -0.58087813 -0.52516981 -0.57138017]


In [13]:
#broadcasting
M = np.array([[1,2,3],
               [4, 5, 6]])
print(M + 100)
row = np.array([10, 20, 30])
print(M + row)

[[101 102 103]
 [104 105 106]]
[[11 22 33]
 [14 25 36]]


In [14]:
#slicing
a = np.array([10,20,30,40,50])
print(a[0])
print(a[-1])
print(a[1:4])
print(a[a > 25])

10
50
[20 30 40]
[30 40 50]


In [15]:
#1
a = np.array([2,4,6,8,10])
print(a + 5)

[ 7  9 11 13 15]


In [26]:
#2
a = np.arange(1,11) 
print(a ** 2) #just print(np.arange(1,11) ** 2)

[  1   4   9  16  25  36  49  64  81 100]


In [31]:
#3,4,5
a = np.array([3,1,4,1,5,9,2,6])
print(np.sum(a))
print(np.mean(a))
print(np.std(a)) #FOR VOLATILITY

31
3.875
2.5708704751503917


In [32]:
#6
a = np.random.standard_normal(1000)
print(np.mean(a))
print(np.std(a)) #because

0.024635411011208103
1.0003245197831303


In [35]:
#7
a = np.array([3, 4])
print(a / np.sqrt(np.sum(a**2)))

[0.6 0.8]


In [37]:
#8
a = np.array([[1, 2],
             [3, 4]])
b = np.array([[5, 6],
             [7, 8]])
print(a *b)

[[ 5 12]
 [21 32]]


In [42]:
#9
a = np.arange(0,20) 
print(a[a > 10])

[11 12 13 14 15 16 17 18 19]


In [44]:
#10
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([1, 1, 1])
print(a - b)

[[0 1 2]
 [3 4 5]]
