In [1]:
import numpy as np

In [4]:
np.zeros((2, 3)) #filled w/ 0s 2 rows, 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((3, 3)) #filled w/ 1s

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.arange(12) #1d rowa of 12 numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
np.arange(2, 20, 3) # starts at 2 until 20, interval 3

array([ 2,  5,  8, 11, 14, 17])

In [9]:
np.linspace(0, 1, 5) # from 1 to 1, 5 points

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.arange(12).reshape(3, 4) #from 0 to 11, in matrix 3/4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
#1
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
#2
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
#3
x = np.arange(12).reshape(3, 4)
x.sum(axis=1) #collapse every row to 1 number

array([ 6, 22, 38])

In [14]:
#4
x = np.arange(12).reshape(3, 4)
x.sum(axis=0) #collapse every column to 1 number

array([12, 15, 18, 21])

In [16]:
#5
x = np.ones((4, 4))
x.sum()

np.float64(16.0)